//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaestroSignant.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaestroSignant.Infrastructure.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update PostingSyncJob
        ///Set SyncStatus = @SyncStatus, ModifiedDate = @ModifiedDate
        ///where PostingId = @PostingId.
        /// </summary>
        internal static string CompletePostingSyncJob {
            get {
                return ResourceManager.GetString("CompletePostingSyncJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select AttachmentName as Name, ContentType, AttachmentSignedData as Data
        ///from Posting
        ///where Posting = @Posting and AttachmentId = @AttachmentId.
        /// </summary>
        internal static string GetAttachment {
            get {
                return ResourceManager.GetString("GetAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select posting.PostingId,
        ///	   posting.AttachmentId,
        ///	   person.PersonId, 
        ///	   person.Name as PersonName, 
        ///	   person.Email as PersonEmail, 
        ///	   posting.AttachmentName, 
        ///	   posting.Status as AttachmentStatus,
        ///	   posting.CreatedDate,
        ///	   posting.ModifiedDate
        ///from Person as person
        ///inner join Posting as posting on person.PersonId = posting.PersonId.
        /// </summary>
        internal static string GetPersonPostings {
            get {
                return ResourceManager.GetString("GetPersonPostings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select job.Id, job.PostingId, posting.AttachmentId
        ///from PostingSyncJob as job
        ///inner join Posting as posting on posting.PostingId = job.PostingId
        ///where job.SyncStatus = @SyncStatus.
        /// </summary>
        internal static string GetPostingSyncJobs {
            get {
                return ResourceManager.GetString("GetPostingSyncJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin transaction
        ///    declare @Id AS uniqueidentifier
        ///
        ///    Select @Id = PersonId From [Person] Where Email = @Email
        ///
        ///    If @Id is null
        ///    Begin
        ///       Insert into [Person] 
        ///       Values (@PersonId, @Name, @Email, @Phone, @Role, @CreatedDate)
        ///    End
        ///    Select @PersonId
        ///Commit transaction.
        /// </summary>
        internal static string InsertPersonIfNotExist {
            get {
                return ResourceManager.GetString("InsertPersonIfNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert into Posting
        ///values (@PostingId, @AttachmentId, @PersonId, @ContentType, 
        ///		@AttachmentName, @AttachmentOriginalData, null, @Status, @CreatedDate, null).
        /// </summary>
        internal static string InsertPosting {
            get {
                return ResourceManager.GetString("InsertPosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert into PostingSyncJob
        ///values (@Id, @SyncStatus, @PostingId, @CreatedDate, null).
        /// </summary>
        internal static string InsertPostingSyncJob {
            get {
                return ResourceManager.GetString("InsertPostingSyncJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select case
        ///        when per.PersonId is not null then 1
        ///        else 0
        ///       end as PersonExists  
        ///from Posting as pos
        ///inner join Person as per on per.PersonId = pos.PersonId
        ///where per.Email = @Email.
        /// </summary>
        internal static string PostingExists {
            get {
                return ResourceManager.GetString("PostingExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Posting
        ///set Status = @Status, AttachmentSignedData = @AttachmentSignedData, ModifiedDate = @ModifiedDate
        ///where PostingId = @PostingId.
        /// </summary>
        internal static string UpdatePosting {
            get {
                return ResourceManager.GetString("UpdatePosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update PostingSyncJob
        ///Set SyncStatus = @SyncStatus, ModifiedDate = @ModifiedDate
        ///where Id = @Id.
        /// </summary>
        internal static string UpdatePostingSyncJob {
            get {
                return ResourceManager.GetString("UpdatePostingSyncJob", resourceCulture);
            }
        }
    }
}
